Algorithms/Graph Theory/Journey to the Moon/solution.py3, README.md
Adding One solution. Was not able to find python solutions, the description says there are.
Looking for feedback on if the style/formatting suits the repo?
Would like to add more as i solve more.
=> Adding Python solution to Journey to Moon.

Algorithms/Dynamic Programming/The Coin Change Problem/solution.py, Algorithms/Strings/Richie Rich/solution.py, README.md
Adding python solution for Coin Change problem and Richie Rich
=> coin change and richie rich

Algorithms/Greedy/Largest Permutation/Solution.js, Algorithms/Greedy/Permuting Two Arrays/Solution.js, Algorithms/Greedy/Priyanka and Toys/Solution.js, README.md
Re-forked the repo and got rid of all the commits. Started adding solutions to README_V2. 
Do we need to also add solutions to original README or is that being deprecated?
=> Completed 3 Greedy JS solutions

Algorithms/Implementation/Matrix Layer Rotation/Python3/Solution.py, Algorithms/Implementation/Matrix Layer Rotation/Solution.py3, README.md
Added Python3 solution for this algorithm implementation.
Updated the README file with the link to the solution.
Need help calculating time and space complexity. Or just leave it to me, will update README with it in couple months.
=> Added Python3 solution for Matrix Layer Rotation

Algorithms/Search/Sherlock and Array, Algorithms/Search/SherlockandArray.cpp
An optimal solution in C++14 to the problem Sherlock and Array in the Search domain of Algorithms
=> Sherlock and Array

Algorithms/Search/Missing Numbers, Algorithms/Search/MissingNumbers.cpp
Solution to the Missing Numbers problem from HackerRank.
=> Create Missing Numbers

Algorithms/Implementation/Drawing Book/solution.cs
Added a solution written in C# language for drawing book problem in algorithm section on Hacker rank. I have compiled my C# project targeting .Net framework version 4.5.2.
=> C# solution for drawing book

Algorithms/Implementation/Electronics Shop/solution.cs
Added a solution for electronic shop problem, https://www.hackerrank.com/challenges/electronics-shop/problem. I've created it in C# .Net.
=> Electronic shop problem - C# based solution

Algorithms/Implementation/Drawing Book/Solution.cs
By mistake, earlier I had checked-in the solution of counting the valley problem into this file. I've corrected it. Now, I've added the solution pertaining to the drawing book problem.
=> Corrected the wrongly checked-in solution

Algorithms/Implementation/Drawing Book/Solution.cs
Improved the algorithm steps in thoughts section to make it more crisp for understanding.
=> Drawing book problem: Added more clarity to algorithm steps

Algorithms/Implementation/Jumping on the Clouds- Revisited/Solution.cs
Updated space complexity to O(n) in thoughts section.
=> Updated space complexity in comments

Algorithms/Implementation/Apple and Orange/Solution.cs
Updated algorithm section to make steps more clear.
=> Apple and Orange problem: Updated thoughts

Algorithms/Warmup/Solve Me First/Solution.cs, README.md
Added a new C# based solution for solve me first problem.
=> Solve me first problem: C# solution

Algorithms/Implementation/Encryption/Solution.cs, README.md
I've also modified space complexity to O(1) in readme. O(n) space complexity is not optimal for this solution as there is no run time variable which will vary based on length of input string.
=>  Added a new C# based solution for encryption problem.

DataStructures/Trees/Tree Preorder Traversal/Solution.cpp, README.md
Added a new solution for Tree preorder traversal problem using C++ programming language. The pull request is as per new format.
=>  Tree preorder traversal problem: C++ solution

Algorithms/Implementation/The Time in Words/Solution.cs, README.md
Added a new solution for the time in words problem using C# programming language.
=> The time in words problem: C# solution

DataStructures/Trees/Swap Nodes [Algo]/Solution.cs, README.md
Added a new solution for Swap Nodes [Algo] problem using C# programming language.
=> Swap Nodes [Algo] problem: C# solution

DataStructures/Balanced Trees/Self Balancing Tree/Solution.cpp, README.md
Added a new solution for self balancing tree problem using C++ programming language.
=>  Self balancing tree problem: C++ solution

DataStructures/Heap/QHEAP1/Solution.cs, README.md
Added a new solution for QHEAP1 problem using C# programming language.
=> QHEAP1 problem: C# solution

DataStructures/Multiple Choice/Data Structures MCQ 3/Solution.md, README.md
I've covered all three problems in same pull request as it was just a readme file update. We can't have programming language specific code files corresponding to such type of problems.
=>  Updated readme for multiple choice questions.

DataStructures/Arrays/Arrays - DS/Solution.cpp, README.md
Added a new solution for arrays - ds problem using C++ programming language.
=> Arrays - DS problem: C++ solution

DataStructures/Linked Lists/Print the Elements of a Linked List/Solution.cpp, README.md
Added a new solution for print the elements of a linked list problem using C++ programming language.
=> Print elements of linked list problem:C++ solution

DataStructures/Stacks/Maximum Element/Solution.cpp, README.md
Added a new solution for maximum element problem using C++ programming language.
=> Maximum element problem:C++ solution

Algorithms/Implementation/Lisa's Workbook/Solution.cs, README.md
Added a new solution for Lisa's Workbook problem using C# programming language.
=> Lisa's Workbook problem:C# solution

Algorithms/Sorting/Big Sorting/Solution.cs, README.md
Added a new solution for Big sorting problem using C# programming language.
=> Big sorting problem: C# solution

Algorithms/Sorting/Intro to Tutorial Challenges/Solution.cs, README.md
Added a new solution for intro to tutorial challenges problem using C# programming language.
=> Intro to tutorial challenges: C# solution

Algorithms/Sorting/Insertion Sort - Part 1/Solution.cs, README.md
Added a new solution for insertion sort part I problem using C# programming language.
=> Insertion sort part I problem:C# solution

Algorithms/Sorting/Insertion Sort - Part 2/Solution.cs, README.md
Added a new solution for insertion sort part - 2 problem using C# programming language.
=> Insertion sort part - 2 problem:C# solution

DataStructures/Queues/Queue using Two Stacks/Solution.cs, README.md
Added a new solution for queue using two stacks problem using C# programming language.
=> Queue using two stacks problem:C# solution

DataStructures/Multiple Choice/Data Structures MCQ 1/Solution.md, README.md
It is a language independent solution.
=> added solution for data structures MCQ 1

DataStructures/Multiple Choice/Data Structures MCQ 2/Solution.md, README.md
This is a language independent solution.
=> Added solution for data structures MCQ 2

Algorithms/Sorting/Quicksort 2 - Sorting/Solution.cs, README.md
Added a new solution for Quicksort2 - Sorting problem using C# programming language.
=> Quicksort2 - Sorting problem:C# solution.

README.md
The solution file for this problem was already present in repository but its link was missing from readme file.
=> included solution path of compare two linked lists problem into readme.

README.md
The solution file for this problem was already present in repository but its link was missing from readme file.
=> included solution path of reverse a linked list problem into readme.

README.md
The solution file for this problem was already present in repository but its link was missing from readme file.
=>  included solution path of balanced brackets problem into readme. 

Algorithms/Search/Ice Cream Parlor/Solution.cs, README.md
Added a new solution for Ice Cream parlor problem using C# programming language
=> Ice Cream parlor problem: C# solution

DataStructures/Multiple Choice/Data Structures MCQ 1/Solution.md
Now I've put &nbsp; character whereever we need to have space in the readme file.
=> improved readability with html non breaking space.

DataStructures/Linked Lists/Delete Node/solution.cpp, README.md
Delete a Node from linked list solution
=> solution for deleting the node in linked list 

Algorithms/Implementation/Fair Rations/Solution.cs, README.md
Added a new solution for fair rations problem using C# programming language
=>  Fair rations problem: C# solution 

Algorithms/Search/Ice Cream Parlor/Solution.cs
In previous solution, we were creating a look-up for the  entire array which is not required.
=> Improvised the solution.

Algorithms/Implementation/Cavity Map/Solution.cs, README.md
Added a new solution for cavity map problem using C# programming language.
=> Cavity Map problem: C# solution

Algorithms/Implementation/Manasa and Stones/Solution.cs, README.md
Added a new solution for Manasa and stones problem using C# programming language
=> Manasa and stones problem: C# solution

Mathematics/Fundamentals/Leonardo's Prime Factors/Solution.cs, README.md
Added a new solution for Leonardo's prime factors problem using C# programming language.
=> Leonardo's prime factors problem: C# solution

Algorithms/Strings/Super Reduced String/Solution.cs, README.md
Added a new solution for super reduced string problem using C# programming language.
=> Super reduced string problem: C# solution

README_V2.md
is it helpful to review a couple of typos ?
=> Propose fix some typos

Algorithms/Strings/Mars Exploration/Solution.cs, README.md
Added a new solution for mars exploration problem using C# programming language
=> Mars exploration problem:C# solution

Algorithms/Search/Missing Numbers/Solution.cs, README.md
Added a new solution for missing numbers problem using C# programming language.
=> Missing numbers problem: C# solution

Algorithms/Search/Pairs/Solution.cs, README.md
Added a new solution for pairs problem using C# programming language
=> Pairs problem:C# solution

Algorithms/Search/Gridland Metro/Solution.cs, README.md
Added a new solution for gridland metro problem using C# programming language.
=>  Gridland metro problem: C# solution

Algorithms/Strings/Gemstones/Solution.cs, README.md
Added a new solution for gemstones problem using C# programming language.
=> Gemstones problem: C# solution

Algorithms/Strings/Alternating Characters/Solution.cs, README.md
Added a new solution for alternating characters problem using C# programming language
=> Alternating characters problem:C# solution

DataStructures/Arrays/Sparse Arrays/Solution.cs, README.md
Added a new solution for sparse arrays problem using C# programming language.
=>  Sparse arrays problem: C# solution
